# Generated by Django 3.2.8 on 2021-10-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211015_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodct',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='prodct_image',
            new_name='product_image',
        ),
    ]
