# Generated by Django 3.2.8 on 2021-10-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211021_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
