# Generated by Django 3.2.8 on 2021-11-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211110_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='rejected_post',
            field=models.IntegerField(default=0),
        ),
    ]
