# Generated by Django 3.2.8 on 2021-11-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211117_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
