# Generated by Django 3.2.8 on 2021-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_blocked_useraccount_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='total_liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
    ]
