# Generated by Django 3.2.8 on 2021-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211117_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=80)),
            ],
        ),
    ]
