# Generated by Django 3.2.8 on 2021-12-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_blockusers_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('sports', 'sports'), ('elctronic', 'elctronic'), ('car prts', 'car parts'), ('clothes', 'clothes'), ('education', 'education')], default='', max_length=80, null=True),
        ),
    ]
