# Generated by Django 3.2.8 on 2021-12-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('sports', 'sports'), ('elctronics', 'elctronics'), ('car parts', 'car parts'), ('clothes', 'clothes'), ('education', 'education')], default='', max_length=80, null=True),
        ),
    ]
