# Generated by Django 3.2.8 on 2021-12-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211229_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(choices=[('Amman', 'Amman'), ('Jarash', 'Jarash')], default='', max_length=80),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='st_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
