# Generated by Django 3.2.8 on 2021-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211229_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='location',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(choices=[('Amman', 'Amman'), ('Jarash', 'Jarash')], default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='st_name',
            field=models.CharField(default='', max_length=80, verbose_name='street name'),
        ),
    ]
