# Generated by Django 3.2.8 on 2021-12-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211229_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
