# Generated by Django 3.2.8 on 2021-12-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_delete_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='st_name',
        ),
    ]
