# Generated by Django 3.2.8 on 2021-12-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211229_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='address',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='city',
            field=models.CharField(choices=[('amman', 'Amman'), ('jarash', 'Jarash')], default='', max_length=80),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='st_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
