# Generated by Django 3.2.8 on 2022-01-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211230_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='accepted_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='total_post',
            field=models.IntegerField(default=0),
        ),
    ]
