# Generated by Django 3.2.8 on 2022-01-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220104_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='total_post',
            new_name='total_posts',
        ),
    ]
