# Generated by Django 3.2.8 on 2022-01-10 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_requested_book_requestedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedbook',
            old_name='product',
            new_name='user',
        ),
    ]
