# Generated by Django 3.2.8 on 2022-01-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20220111_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedbook',
            old_name='requetd_user',
            new_name='requestd_user',
        ),
    ]
