# Generated by Django 3.2.8 on 2022-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_requetd_user_requestedbook_requestd_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedbook',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestedbook',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestedbook',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
