# Generated by Django 3.2.8 on 2022-01-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_requestedbook_requestd_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='booked_requests',
            field=models.IntegerField(default=0),
        ),
    ]
