# Generated by Django 3.2.8 on 2022-01-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_useraccount_booked_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('elctronics', 'Elctronics'), ('car parts', 'Car parts'), ('clothes', 'Clothes'), ('education', 'Education')], default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
